const ShopActionType = {
  FETCH_COLLECTIONS_START: "UPDATE_COLLECTION",
  FETCH_COLLECTIONS_SUCESS: "FETCH_COLLECTIONS_SUCESS",
  FETCH_COLLECTIONS_FAILURE: "FETCH_COLLECTIONS_FAILURE",
};

export default ShopActionType;
